fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-xml
      - id: fix-byte-order-marker
      - id: destroyed-symlinks
      - id: fix-encoding-pragma
      - id: check-ast

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.85.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
        args:
          - '--args=--enable-rule=terraform_unused_declarations'
          - '--args=--enable-rule=terraform_naming_convention'
          - '--args=--enable-rule=terraform_deprecated_index'
          - '--args=--enable-rule=terraform_comment_syntax'
          - '--args=--enable-rule=terraform_documented_outputs'
          - '--args=--enable-rule=terraform_documented_variables'
          - '--args=--enable-rule=terraform_typed_variables'
          - '--args=--enable-rule=terraform_deprecated_interpolation'
          - '--args=--enable-plugin=tps-codestyle'
          - '--args=--disable-rule=terraform_module_pinned_source'
          - '--args=--disable-rule=terraform_required_providers'
          - '--args=--disable-rule=terraform_deprecated_interpolation'
      - id: terraform_docs
        args:
          - --args=--config=.terraform-docs.yml
      # - id: terraform_tfsec

  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.18
    hooks:
    - id: circleci-config-validate
    - id: shellcheck

  -   repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.10.0  # Use the ref you want to point at
      hooks:
      -   id: python-use-type-annotations

  -   repo: https://github.com/asottile/reorder-python-imports
      rev: v3.12.0
      hooks:
      -   id: reorder-python-imports

  -   repo: https://github.com/asottile/setup-cfg-fmt
      rev: v2.5.0
      hooks:
      -   id: setup-cfg-fmt

  -   repo: https://github.com/pycqa/flake8
      rev: '6.1.0'
      hooks:
      -   id: flake8
